# MOE-INVEST Configuration File
# 실험 설정 및 파라미터

# 백테스트 기간 설정
backtest:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 100000000  # 1억원
  rebalancing_frequency: "monthly"  # monthly, quarterly, weekly

# 에이전트 설정
agents:
  graham:
    enabled: true
    max_pe: 15
    max_pb: 1.5
    min_current_ratio: 2.0
    max_debt_equity: 0.5
    min_roe: 0.10
    
  piotroski:
    enabled: true
    min_f_score: 7
    min_market_cap: 1000000000  # 10억원
    
  greenblatt:
    enabled: true
    min_market_cap: 50000000000  # 500억원
    min_roic: 0.05
    max_ev_ebit: 50
    
  carlisle:
    enabled: true
    momentum_period: 252  # 1년
    min_momentum: 0.05
    volatility_period: 60
    min_market_cap: 10000000000  # 100억원
    
  driehaus:
    enabled: true
    min_revenue_growth: 0.15
    min_earnings_growth: 0.20
    min_market_cap: 50000000000  # 500억원
    max_pe: 50
    momentum_period: 60

# 포트폴리오 설정
portfolio:
  max_stocks: 20
  max_sector_weight: 0.3
  min_stock_weight: 0.01
  max_stock_weight: 0.1
  min_liquidity: 1000000000  # 10억원

# CoT 추론 설정
meta_agent:
  consensus_threshold: 0.5  # 50% 이상의 에이전트가 추천
  max_final_stocks: 20
  llm_enabled: false  # 실제 LLM 사용 여부

# 데이터 설정
data:
  data_dir: "data"
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  
  # 데이터 소스 설정
  sources:
    market_data: "sample"  # sample, api, database
    financial_data: "sample"
    economic_data: "sample"
    
  # 전처리 설정
  preprocessing:
    fill_method: "ffill"  # forward fill
    outlier_method: "3sigma"  # 3시그마 규칙
    min_data_points: 100

# 백테스트 결과 설정
results:
  output_dir: "results"
  save_charts: true
  save_reports: true
  save_data: true
  
  # 성과 평가 설정
  evaluation:
    risk_free_rate: 0.02  # 2%
    benchmark: "KOSPI"  # 벤치마크 지수
    rolling_window: 252  # 1년

# 로깅 설정
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "logs/moe_invest.log"
  console_output: true

# 실험 설정
experiment:
  name: "moe_invest_demo"
  description: "MOE-INVEST 시스템 데모 실험"
  tags: ["demo", "multi_agent", "quantitative"]
  
  # 실험 변수
  variables:
    - name: "rebalancing_frequency"
      values: ["monthly", "quarterly"]
    - name: "consensus_threshold"
      values: [0.3, 0.5, 0.7]
    - name: "max_stocks"
      values: [10, 20, 30]

# API 설정 (실제 데이터 사용 시)
api:
  enabled: false
  endpoints:
    market_data: "https://api.example.com/market"
    financial_data: "https://api.example.com/financial"
    economic_data: "https://api.example.com/economic"
  
  # 인증 설정
  authentication:
    api_key: ""
    secret_key: ""
    
  # 요청 제한
  rate_limits:
    requests_per_minute: 60
    requests_per_hour: 1000

# 데이터베이스 설정 (데이터베이스 사용 시)
database:
  enabled: false
  type: "postgresql"  # postgresql, mysql, sqlite
  host: "localhost"
  port: 5432
  database: "moe_invest"
  username: ""
  password: ""
  
  # 테이블 설정
  tables:
    market_data: "market_data"
    financial_data: "financial_data"
    economic_data: "economic_data"
    backtest_results: "backtest_results"

# 성능 최적화 설정
performance:
  # 병렬 처리 설정
  parallel:
    enabled: true
    max_workers: 4
    
  # 메모리 최적화
  memory:
    chunk_size: 10000
    cache_enabled: true
    
  # 계산 최적화
  computation:
    use_numba: false  # Numba JIT 컴파일러 사용
    use_gpu: false    # GPU 가속 사용

# 시각화 설정
visualization:
  style: "seaborn-v0_8"
  figure_size: [12, 8]
  dpi: 300
  save_format: "png"
  
  # 차트 색상 설정
  colors:
    primary: "#1f77b4"
    secondary: "#ff7f0e"
    success: "#2ca02c"
    warning: "#d62728"
    info: "#9467bd"

# 보안 설정
security:
  # 데이터 암호화
  encryption:
    enabled: false
    algorithm: "AES-256"
    
  # 접근 제어
  access_control:
    enabled: false
    allowed_ips: []
    api_key_required: true

# 모니터링 설정
monitoring:
  enabled: true
  
  # 성능 모니터링
  performance:
    track_execution_time: true
    track_memory_usage: true
    track_cpu_usage: true
    
  # 알림 설정
  alerts:
    email_enabled: false
    slack_enabled: false
    webhook_enabled: false
    
    # 알림 조건
    conditions:
      - type: "error_rate"
        threshold: 0.05
      - type: "execution_time"
        threshold: 3600  # 1시간
      - type: "memory_usage"
        threshold: 0.8   # 80%

# 개발/디버깅 설정
development:
  debug_mode: false
  verbose_output: false
  
  # 테스트 설정
  testing:
    enabled: false
    test_data_size: 1000
    mock_agents: true
    
  # 프로파일링
  profiling:
    enabled: false
    profile_file: "profile_results.prof" 